name: Continuous Integration

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches:
      - '*'
      
jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15.4-alpine
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: database_test
        ports:
          - 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgresql://root:root@localhost:5432/database_test?schema=public&connect_timeout=30
      AT_SECRET: AT_sECRET
      RT_SECRET: RT_sECRET
      TK_EMAIL_SECRET: EMAIL_sECRET
      TK_EMAIL_LIFETIME: 1d
      JWT_ACCESS_LIFETIME: 1h
      JWT_REFRESH_LIFETIME: 7d
      ENV: TEST

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '20.11.0'

    - name: Install NPM dependencies
      run: npm install

    - name: Wait for Database Initialization
      run: |
        sleep 60

    - name: Apply database migrations
      run: npm run prisma:migrate
    
    - name: Run auth tests
      run: npm test:auth

    - name: Run user tests
      run: npm test:user